@api = http://localhost:4000

GET {{api}}/videos

###
GET {{api}}/videos/1

### Create a video
POST {{api}}/videos
Content-Type: application/json

{
    "url": "https://www.youtube.com/watch?v=_RZ-T6TxP7w&t=887s",
    "title": "fazt",
    "description": "A new MERN video"
}
###
DELETE {{api}}/videos/1

###
PATCH {{api}}/videos/1
