@api = http://localhost:4000

GET {{api}}/videos

###
GET {{api}}/videos/60eb9c01f7b5162918563aab

### Create a video
POST {{api}}/videos
Content-Type: application/json

{
    "url": "https://www.youtube.com/watch?v=_RZ-T6TxP7w&t=887s",
    "title": "fazt",
    "description": "A new MERN video"
}
###
DELETE {{api}}/videos/60eb9c01f7b5162918563aab

###
PUT {{api}}/videos/60eb9c01f7b5162918563aab
Content-Type: application/json

{
    "title": "MERN Application"
}